server:
  port: 2001

spring:
  application:
    name: seata-order-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 159357asd
  cloud:
    nacos:
      discovery:
        #配置Nacos地址
        server-addr: localhost:8848

feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info

seata:
  enabled: true
  tx-service-group: seata-mall # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  service:
    vgroup-mapping:  # TC 集群（必须与seata-server保持一致）
      seata-mall: default
    disable-global-transaction: false # 禁用全局事务（默认false）

